# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Exercise OLMo KDA radix-cache reuse and cached-continuation parity."""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any

from olmo_sglang import register

LOGGER = logging.getLogger(__name__)


def _create_engine(model_path: Path, *, disable_radix_cache: bool) -> Any:
    """Create the correctness-first tiny-checkpoint SGLang engine."""

    import sglang as sgl

    return sgl.Engine(
        model_path=str(model_path),
        trust_remote_code=True,
        skip_tokenizer_init=True,
        dtype="float16",
        cuda_graph_backend_decode="disabled",
        cuda_graph_backend_prefill="disabled",
        disable_radix_cache=disable_radix_cache,
        attention_backend="torch_native",
        context_length=32,
        max_total_tokens=64,
        max_mamba_cache_size=4,
        mem_fraction_static=0.15,
    )


def _generate(engine: Any, input_ids: list[int], max_new_tokens: int) -> dict[str, Any]:
    output = engine.generate(
        input_ids=input_ids,
        sampling_params={"temperature": 0, "max_new_tokens": max_new_tokens},
    )
    return {
        "input_ids": input_ids,
        "output_ids": output["output_ids"],
        "cached_tokens": int(output["meta_info"]["cached_tokens"]),
    }


def _generate_batch(
    engine: Any, input_ids: list[int], max_new_tokens: int, repeats: int
) -> list[dict[str, Any]]:
    """Submit identical prompts together as one scheduler batch."""

    outputs = engine.generate(
        input_ids=[input_ids for _ in range(repeats)],
        sampling_params={"temperature": 0, "max_new_tokens": max_new_tokens},
    )
    if not isinstance(outputs, list):
        raise TypeError(f"Expected a batch of SGLang outputs, got {type(outputs)!r}")
    return [
        {
            "input_ids": input_ids,
            "output_ids": output["output_ids"],
            "cached_tokens": int(output["meta_info"]["cached_tokens"]),
        }
        for output in outputs
    ]


def run_radix_smoke(
    model_path: Path, input_ids: list[int], max_new_tokens: int
) -> dict[str, Any]:
    """Compare a cache-hit continuation with an uncached continuation.

    The first cache-enabled generation creates a complete recurrent-state
    checkpoint. The second request continues from that exact history, requiring
    SGLang to copy both the convolution window and KDA matrix from the radix
    node. A fresh cache-disabled engine then recomputes the same continuation.

    Args:
        model_path: Tiny OLMo KDA checkpoint directory.
        input_ids: Initial prompt token IDs.
        max_new_tokens: Greedy tokens generated in each turn.

    Returns:
        JSON-serializable warm, cached, and uncached generation details.

    Raises:
        AssertionError: If no prefix was reused or cached output changes.
    """

    register()
    cached_engine = _create_engine(model_path, disable_radix_cache=False)
    try:
        warm = _generate(cached_engine, input_ids, max_new_tokens)
        continuation_input = input_ids + warm["output_ids"]
        cached = _generate(cached_engine, continuation_input, max_new_tokens)
    finally:
        cached_engine.shutdown()

    uncached_engine = _create_engine(model_path, disable_radix_cache=True)
    try:
        uncached = _generate(uncached_engine, continuation_input, max_new_tokens)
    finally:
        uncached_engine.shutdown()

    if cached["cached_tokens"] <= 0:
        raise AssertionError(f"Expected a KDA radix-cache hit, got {cached!r}")
    if cached["output_ids"] != uncached["output_ids"]:
        raise AssertionError(
            "KDA radix state changed greedy continuation: "
            f"cached={cached['output_ids']}, uncached={uncached['output_ids']}"
        )
    return {"warm": warm, "cached": cached, "uncached": uncached}


def run_repeated_prompt_probe(
    model_path: Path,
    input_ids: list[int],
    max_new_tokens: int,
    repeats: int,
) -> dict[str, Any]:
    """Compare sequential and simultaneous submissions of one prompt.

    The sequential and simultaneous halves reveal whether ordinary completed
    requests leave a reusable state at the prompt boundary. The seeded half
    first completes ``input_ids[:-1]`` with one throwaway token, creating the
    exact recurrent-state boundary needed by a batch of full-prompt requests.

    Args:
        model_path: Tiny OLMo KDA checkpoint directory.
        input_ids: Prompt token IDs repeated in every request.
        max_new_tokens: Greedy tokens generated by each request.
        repeats: Number of identical requests per experiment.

    Returns:
        JSON-serializable sequential and simultaneous request details.

    Raises:
        AssertionError: If seeded reuse does not occur or greedy outputs differ
            across identical requests.
        ValueError: If fewer than two requests or input tokens are specified.
    """

    if repeats < 2:
        raise ValueError(f"repeats must be at least 2, got {repeats}")
    if len(input_ids) < 2:
        raise ValueError("input_ids must contain at least two tokens")

    register()
    sequential_engine = _create_engine(model_path, disable_radix_cache=False)
    try:
        sequential = [
            _generate(sequential_engine, input_ids, max_new_tokens)
            for _ in range(repeats)
        ]
    finally:
        sequential_engine.shutdown()

    simultaneous_engine = _create_engine(model_path, disable_radix_cache=False)
    try:
        simultaneous = _generate_batch(
            simultaneous_engine, input_ids, max_new_tokens, repeats
        )
    finally:
        simultaneous_engine.shutdown()

    seeded_engine = _create_engine(model_path, disable_radix_cache=False)
    try:
        seed = _generate(seeded_engine, input_ids[:-1], 1)
        seeded_simultaneous = _generate_batch(
            seeded_engine, input_ids, max_new_tokens, repeats
        )
    finally:
        seeded_engine.shutdown()

    if any(item["cached_tokens"] <= 0 for item in seeded_simultaneous):
        raise AssertionError(
            "Expected the explicit prompt-boundary seed to produce cache hits, "
            f"got seed={seed!r}, requests={seeded_simultaneous!r}"
        )
    expected_output = sequential[0]["output_ids"]
    all_outputs = sequential[1:] + simultaneous + seeded_simultaneous
    if any(item["output_ids"] != expected_output for item in all_outputs):
        raise AssertionError(
            "Identical greedy requests produced different outputs: "
            f"sequential={sequential!r}, simultaneous={simultaneous!r}, "
            f"seeded_simultaneous={seeded_simultaneous!r}"
        )
    return {
        "sequential": sequential,
        "simultaneous": simultaneous,
        "seeded_simultaneous": {"seed": seed, "requests": seeded_simultaneous},
    }


def parse_args() -> argparse.Namespace:
    """Parse tiny radix-cache smoke-test arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, required=True)
    parser.add_argument("--input-ids", type=int, nargs="+", default=[2, 3, 4, 5])
    parser.add_argument("--max-new-tokens", type=int, default=4)
    parser.add_argument(
        "--repeat-prompt-probe",
        action="store_true",
        help="Compare repeated sequential requests with one simultaneous batch.",
    )
    parser.add_argument("--repeats", type=int, default=3)
    return parser.parse_args()


def main() -> None:
    """Run the smoke test and emit its machine-readable result."""

    logging.basicConfig(level=logging.INFO, format="%(message)s")
    LOGGER.setLevel(logging.INFO)
    args = parse_args()
    if args.repeat_prompt_probe:
        report = run_repeated_prompt_probe(
            args.model, args.input_ids, args.max_new_tokens, args.repeats
        )
    else:
        report = run_radix_smoke(args.model, args.input_ids, args.max_new_tokens)
    LOGGER.info("%s", json.dumps(report, sort_keys=True))


if __name__ == "__main__":
    main()
